### ISSUE TITLE
讨论

### ISSUE THREAD

**Issue by XieZongChen** [07akioni/ilw#1]
感觉可以将埋点功能也结合进来

**Comment by XieZongChen** [comment]
我看README里只提到可以兼容公司埋点工具

**Comment by 07akioni** [comment]
> 我看README里只提到可以兼容公司埋点工具

因为只是个适配器而已，所以不会和某个具体工具绑定

**Comment by 07akioni** [comment]
目标是对于不同的埋点、监控、上报工具给一个统一的出口

**Comment by 07akioni** [comment]
那我们说一个最简单的情况，就是你只有一个 web app，并且只用 sentry，那么这个工具就价值不大
